import Head from 'next/head'
import styles from '../../styles/Anime.module.css'
import Footer from '../../components/footer'

export const getStaticProps = async () => {

  const res = await fetch('https://api.jikan.moe/v3/top/anime');
  const data = await res.json();

  return {
    props: { anime: data }
  }
}

export default function Anime({ anime }) {
  return (
    <div>
      <Head>
        <title>Next Anime | Anime</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/NextAnimeLogo.png" />
      </Head>

      <main className={styles.container}>
        {anime.top.map(res => console.log(res.title
        ))}
      </main>
      <Footer />
    </div >
  )
}
