import Head from 'next/head'
import styles from '../../styles/Anime.module.css'
import Footer from '../../components/footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Anime | Anime</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/NextAnimeLogo.png" />
      </Head>

      <main className={styles.container}>
      </main>
      <Footer />
    </div >
  )
}
