import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from '../components/footer'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Anime | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/NextAnimeLogo.png" />
      </Head>

      <main className={styles.main}>
        <Image src="/NextAnimeLogo.png" width={128} height={128} />
        <Link href="/anime">
          <button>Check out the top 50 Anime!</button>
        </Link>
      </main>
      <Footer />

    </div >
  )
}
