import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from '../components/footer'
import Image from 'next/image'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Anime</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src="/NextAnimeLogo.png" width={128} height={128} />
      </main>
      <Footer />

    </div >
  )
}
